---
- name: Instalación de dependencias
  apt: 
    name: ['qemu-kvm', 'libvirt-clients', 'libvirt-daemon-system', 'bridge-utils', 'virtinst', 'libvirt-daemon', 'virt-manager']
    update_cache: yes
    cache_valid_time: 3600

- name: Iniciando y activando al inicio libvirtd
  systemd:
    name: libvirtd.service
    state: started
    enabled: yes

- name: Agregar usuarios existentes a grupos
  user:
    name: "{{ usuario }}"
    groups: libvirt,libvirt-qemu
    append: yes

