---
- include_vars: ../../vars_main.yml

- name: Instalación de dependencias
  apt:
    name:
      - qemu-kvm
      - libvirt-clients
      - libvirt-daemon-system
      - bridge-utils
      - virtinst
      - libvirt-daemon
      - virt-manager
      - build-essential
      - libxslt-dev
      - libxml2-dev
      - libvirt-dev
      - zlib1g-dev
      - ruby-dev
    update_cache: true
    cache_valid_time: 3600

- name: Iniciando y activando al inicio libvirtd
  systemd:
    name: libvirtd.service
    state: started
    enabled: true

- name: Agregar usuarios existentes a grupos
  user:
    name: "{{ usuario }}"
    groups: libvirt,libvirt-qemu
    append: true

- name: Listando plugins
  command: "vagrant plugin list"
  changed_when: false
  register: vagrant_plugins

- name: Instalando plugins
  command: "vagrant plugin install vagrant-libvirt"
  when:
    - '"vagrant-libvirt" not in vagrant_plugins.stdout'
  become: true
  become_user: "{{ usuario }}"
