---
- name: Importar la llave
  apt_key:
    state: present
    url: https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg

- name: Agrega los repos
  apt_repository:
    repo: deb https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs/ vscodium main
    state: present
    update_cache: true

- name: Instalación de vscodium
  apt:
    name: codium
    state: present
