---
- include_vars: ../../vars_main.yml

- name: Importar la llave
  apt_key:
    state: present
    url: "{{ vscodium_key }}"

- name: Agrega los repos
  apt_repository:
    repo: deb "{{ vscodium_repo }}" vscodium main
    state: present
    update_cache: true

- name: Instalación de vscodium
  apt:
    name: codium
    state: present
