---
- name: Instalación de dependencias
  apt: 
    name: ['curl']
    state: latest

- name: Descargar y ejecutar el script 
  shell: timeout 90 | sh -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)"
  become: yes
  become_user: "{{ usuario }}"   
