---
- name: Instalación de dependencias
  apt: 
    name: ['nano', 'git']

- name: Mejora en la sintaxis de lenguajes
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: "{{ home  }}/.nano"
  become_user: "{{ user  }}"  	

- name: Inserta líneas al final del archivo
  blockinfile:
    path: "{{ home }}/.nanorc"
    block: |
      set autoindent
      set tabsize 4
      set smooth
      set nowrap
      #set linenumbers

      # disables the shortcut hints
      set nohelp

      # disable inverse text for the minibar
      set titlecolor normal,normal

      # sintax highlighting
      include "~/.nano/*.nanorc" 
    create: yes
    owner: "{{ user }}"
    group: "{{ user }}"
