---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalar nano
  ansible.builtin.apt:
    name: [ 'nano', 'git' ]
    update_cache: true
    cache_valid_time: 3600

- name: Clonar repo
  ansible.builtin.git:
    repo: "{{ nano_repo }}"
    dest: "/home/{{ usuario }}/.nano"
    version: "{{ nano_version }}"
  become_user: "{{ usuario }}"

- name: Copiar config
  ansible.builtin.copy:
    src: files/nanorc
    dest: "/home/{{ usuario }}/.nanorc"
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
    mode: 0770
