---
- include_vars: ../../vars_main.yml

# - name: Installing Packages
# apt:
#   name: "{{ item }}"
#   update_cache: yes
#   cache_valid_time: 3600
# with_items:
#   - nano
#   - git

- name: Instalando dependencias
  apt:
    name:
      - nano
      - git
    update_cache: yes
    cache_valid_time: 3600

- name: Mejora en la sintaxis de lenguajes
  git:
    repo: https://github.com/scopatz/nanorc.git
    dest: "{{ home  }}/.nano"
    version: "{{ nano_version }}"
  become_user: "{{ usuario  }}"

- name: Inserta líneas al final del archivo
  blockinfile:
    path: "{{ home }}/.nanorc"
    block: |
      set autoindent
      set tabsize 4
      set smooth
      set nowrap
      #set linenumbers

      # disables the shortcut hints
      set nohelp

      # disable inverse text for the minibar
      set titlecolor normal,normal

      # sintax highlighting
      include "~/.nano/*.nanorc"
    create: true
    mode: '0440'
    owner: "{{ usuario }}"
    group: "{{ usuario }}"
