---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Importar llave
  ansible.builtin.apt_key:
    url: "{{ brave_url }}/brave-core.asc"
    state: present

- name: Agregar repo
  ansible.builtin.apt_repository:
    repo: deb "{{ brave_url }}" stable main
    state: present
    update_cache: true

- name: Instalar brave
  ansible.builtin.apt:
    name: [ 'brave-browser', 'software-properties-common', 'apt-transport-https' ]

