---
- include_vars: ../../vars_main.yml

- name: Instalación de dependencias
  apt:
    name: [ 'software-properties-common', 'apt-transport-https' ]
    update_cache: true
    cache_valid_time: 3600

- name: Importar llave
  apt_key:
    url: "{{ brave_url }}/brave-core.asc"
    state: present

- name: Agregar repo
  apt_repository:
    repo: deb "{{ brave_url }}" stable main
    state: present
    update_cache: true

- name: Instalar Brave
  apt:
    name: brave-browser
    state: present
