---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalar dependencias
  ansible.builtin.apt:
    name: [ 'python3-venv', 'pipx' ]
    update_cache: true
    cache_valid_time: 3600

- name: Instalar python-tools
  ansible.builtin.shell: |
    pipx ensurepath
    pipx install impacket
    pipx install crackmapexec
  become_user: "{{ usuario }}"